name: deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      project_dir:
        description: "Relative path to the Node.js project (e.g., ./src)"
        required: false
        default: "./"

jobs:
  prod:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.project_dir || './' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Diagnóstico del entorno
        run: |
          echo "Directorio del proyecto: ${PROJECT_DIR}"
          echo "Uso de disco:" && df -h
          echo "Versión de Node:" && node --version
          echo "Versión de npm:" && npm --version
          echo "Variables de entorno:" && env | sort

      - run: npm ci
        working-directory: ${{ env.PROJECT_DIR }}
      - run: npm run build
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Stamp version
        run: |
          echo "sha=${GITHUB_SHA}" > dist/DEPLOY_TAG.txt
          date -u +"time=%Y-%m-%dT%H:%M:%SZ" >> dist/DEPLOY_TAG.txt
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Trust host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync dist -> VPS
        run: |
          rsync -rltgoDzvO --delete dist/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/srv/web_staff/html/
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Restart + verify
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "docker restart web_staff"
          curl -s https://staff.tamburiniserviteca.cl/DEPLOY_TAG.txt || true
