name: deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run build

      - name: Stamp version
        run: |
          echo "sha=${GITHUB_SHA}" > dist/DEPLOY_TAG.txt
          date -u +"time=%Y-%m-%dT%H:%M:%SZ" >> dist/DEPLOY_TAG.txt

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Trust host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync dist -> VPS
        run: |
          rsync -rltgoDzvO --delete dist/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/srv/web_staff/html/

      - name: Restart + verify
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "docker restart web_staff"
          curl -s https://staff.tamburiniserviteca.cl/DEPLOY_TAG.txt || true
