name: deploy
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build

      # Subir build al VPS (rsync atómico con --delete)
      - name: Upload dist to VPS
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST || '82.25.65.219' }}
          REMOTE_USER: ${{ secrets.VPS_USER || 'root' }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.VPS_TARGET || '/srv/web_staff/html/' }}
          ARGS: "-rltgoDzvO --delete"

      - name: Restart container
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER || 'root' }}@${{ secrets.VPS_HOST || '82.25.65.219' }} "docker restart web_staff"
