- run: npm ci && npm run build

# Sella versión dentro del build
- name: Stamp version
  run: |
    echo "sha=${GITHUB_SHA}" > dist/DEPLOY_TAG.txt
    date -u +"time=%Y-%m-%dT%H:%M:%SZ" >> dist/DEPLOY_TAG.txt

# Carga clave y confía en el host
- uses: webfactory/ssh-agent@v0.9.0
  with: { ssh-private-key: ${{ secrets.VPS_SSH_KEY }} }
- run: |
    mkdir -p ~/.ssh
    ssh-keyscan -p 22 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

# Publica EXACTAMENTE al docroot
- name: Rsync dist -> VPS
  run: rsync -rltgoDzvO --delete dist/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/srv/web_staff/html/

# Reinicia y verifica
- run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "docker restart web_staff"
    curl -s https://staff.tamburiniserviteca.cl/DEPLOY_TAG.txt
ST }} "docker restart web_staff"
